### ISSUE TITLE
Allow triggering actions with no handlers?

### ISSUE THREAD

**Issue by martikaljuve** [BlackDice/scent#3]
[docs/engine.md](docs/engine.md) states:

> Note that trying to trigger action without single registered handler will basically throw away such actions. This is to prevent stacking up in memory without anyone interested.

I thought this would mean that I can use engine.triggerAction(...) without having any engine.onAction(...) handlers, but apparently that's not allowed?

``` javascript
var Scent = require('scent');
var engine = new Scent.Engine();

engine.start();

var cDoor = new Scent.Component('door', 'open');
var door = new cDoor();

// no .onAction handler!

engine.triggerAction('doorOpen', door);

engine.update();
```

Results in:
`Uncaught TypeError: Cannot read property 'length' of undefined
node_modules\scent\lib\scent-browser.js:670`

Using release 0.7.1 from the repository.

**Comment by danielkcz** [comment]
Actions are not pub/sub events or whatever you like to call it. Since `triggerAction` call actually stores data and these are not thrown away till something actually reads them, it would cause actions being stored in memory and just growing. Thus if there is no onAction handler, nothing is stored.

Actions are not meant to be used like Mediator pattern. Main use for us is for transferring user interaction over the network and we needed some consistent state there. Using pub/sub would be too troublesome. It doesn't really make any sense trying to use triggerAction and not having any consumer for it.

However it shouldn't throw an exception. Thanks for the report, I'll look into it when I get some time.

**Comment by martikaljuve** [comment]
Cool, thanks for the explanation. Actions seemed the easiest way to get mouse/touch events into the engine, so I created a bunch of placeholder actions for tap, pan etc, which caused the exception:

``` javascript
var Hammer = require('hammer'); // Hammer.js

var hammer = new Hammer(document.body);

hammer.on('tap', function(ev) {
    engine.triggerAction('tap', { pageX: ev.center.x, pageY: ev.center.y });
})

hammer.on('panstart', function(ev) {
    engine.triggerAction('panstart', { pageX: ev.center.x, pageY: ev.center.y });
})

/../
```

**Comment by danielkcz** [comment]
Yeah definitely good way to use actions since rendering optimizer will be much happier when you process user interaction events in planned manner during update loop. Handling such events whenever they occur can cause some frames being skipped in extreme situations.

I would probably recommend creating system (or even more) which uses hammer directly to add event listener and trigger action. Then in the same system you use `onAction`. This way you can be sure there is at least one consumer and optionally you can process that action elsewhere too.

**Comment by danielkcz** [comment]
Published to NPM as 0.7.2

**Comment by martikaljuve** [comment]
> I would probably recommend creating system (or even more) which uses hammer directly to add event listener and trigger action. Then in the same system you use `onAction`.

That's exactly what I've done so far:

``` javascript
//systems/touch_system.js

/../

class TouchSystem {
    constructor($engine) {
        if (!(this instanceof TouchSystem)) {
            return new TouchSystem($engine);
        }

        this.hammer = new Hammer($engine.options.container);

        this.hammer.on('tap', function(ev) {
            $engine.triggerAction('tap', { pageX: ev.center.x, pageY: ev.center.y });
        });

        /../

        // HACK: No-ops
        $engine.onAction('tap', function(action) {
            // console.log(action.data);
        });
    }
}
```

``` javascript
//main.js

/../

this.engine = new Scent.Engine(function(engine) {
    engine.options = {
        container: document.body
    };
});

this.engine.addSystem(TouchSystem);

/../
```

Thanks for the quick fix!

**Comment by danielkcz** [comment]
@martikaljuve May I ask why are you creating system as class? Just wondering because it seems unnecessary. System can be simply just a function. You could skip all that mess with `constructor` and stuff. It's just about that system is not supposed to be something complex with a methods, properties and inheritance. But if that works for you, not a problem.

**Comment by martikaljuve** [comment]
I guess I've gone a bit overboard with ES6 features. I liked the cleanliness of the class syntax, and since I'm using an [es6 transpiler](https://www.npmjs.com/package/es6-browserify) transform in browserify, they get converted into functions anyway (without having to use the Traceur runtime.)

**Comment by danielkcz** [comment]
@martikaljuve I suppose it's fine, but for the case of the systems it seems even more appropriate having just a function in source code. Once you have class there it tends to go wrong way and before you realize it, there will be deep inheritance tree of systems and weird methods :) Just my guess, it's your call obviously.

Btw, I would love to see what you will create with Scent eventually, so let me know when you have something available (you can create new "issue")
